services:
  - type: web
    name: signflow
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        sync: false   # set in Render dashboard
      - key: TURN_URLS
        sync: false   # e.g. turn:openrelay.metered.ca:80,turn:openrelay.metered.ca:443?transport=tcp
      - key: TURN_USER
        sync: false   # e.g. openrelayproject
      - key: TURN_PASS
        sync: false   # e.g. openrelayproject
